// seed/build-sql.ts
// Emits INSERT OR IGNORE statements from PALETTES, so re-running this against an
// already-seeded database is a no-op for rows that already exist: editing an
// existing palette's colors here will NOT update previously-seeded rows. Changing
// already-seeded palette data requires a migration, not a re-seed.
import { writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { PALETTES } from './palettes'

const q = (s: string) => `'${s.replace(/'/g, "''")}'`

const lines: string[] = ['-- Generated by seed/build-sql.ts. Do not edit by hand.']
for (const p of PALETTES) {
  const paletteId = `pal_${p.slug}`
  lines.push(
    `INSERT OR IGNORE INTO palettes (id, slug, name, description, is_default, is_active) ` +
      `VALUES (${q(paletteId)}, ${q(p.slug)}, ${q(p.name)}, ${q(p.description)}, ${p.isDefault ? 1 : 0}, 1);`,
  )
  p.colors.forEach((col, i) => {
    lines.push(
      `INSERT OR IGNORE INTO palette_colors (id, palette_id, hex, name, position) ` +
        `VALUES (${q(`${p.slug}-${i}`)}, ${q(paletteId)}, ${q(col.hex)}, ${q(col.name)}, ${i});`,
    )
  })
}

const outPath = join(dirname(fileURLToPath(import.meta.url)), 'seed.sql')
writeFileSync(outPath, lines.join('\n') + '\n')
console.log(`Wrote ${outPath} (${PALETTES.length} palettes)`)
